### ISSUE TITLE
Ожидаемая проекция - WGS84

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_opendata#16]
Плагины OL и lefleat видимо ожидают данные в градусах. В результате просмотр не работает
http://176.9.38.120/opendata/dataset/bojic/resource/70339380-0d7a-4094-8e39-441d18f49d63

Тут либо исправить плагин либо сделать выдачу geoJSON в перепроецированном виде.

**Comment by drnextgis** [comment]
А как посмотреть этот ресурс в OL? Для Leaflet-а я починил, создал у себя [репозиторий](https://github.com/drnextgis/ckanext-geoview/tree/proj4leaflet) и перевёл на него наш инстанс. Будем пробовать протолкнуть в апстрим.

**Comment by BishopGIS** [comment]
Добавил еще один вид карты 
http://176.9.38.120/opendata/dataset/bojic/resource/70339380-0d7a-4094-8e39-441d18f49d63?view_id=e417be2b-4b28-4710-9ded-6f0008f0e966

**Comment by simgislab** [comment]
чет не показывает ничего у меня по ссылке

**Comment by drnextgis** [comment]
По ссылке из первого поста ничего не показывает?

**Comment by BishopGIS** [comment]
@simgislab Попробуй залогинится (логин/пароль стандартные) - я пока этот ресурс не открывал.

**Comment by BishopGIS** [comment]
![2015-11-25 14 40 47](https://cloud.githubusercontent.com/assets/1708122/11396460/a98edd24-9382-11e5-8e48-511921846c45.png)

**Comment by simgislab** [comment]
все ок, у меня не работала вкладка OL Map оказывается (вторая ссылка здесь), мне кажется ее нужно отключить совсем, зачем она?

**Comment by BishopGIS** [comment]
Я ее для @drnextgis добавил
```
А как посмотреть этот ресурс в OL? Для Leaflet-а я починил
```

**Comment by simgislab** [comment]
не тратьте время на это, нам достаточно одной карты

**Comment by BishopGIS** [comment]
Это @drnextgis захотел. Я ему также написал.

**Comment by drnextgis** [comment]
@BishopGIS отключи тогда вкладку с OL.

**Comment by BishopGIS** [comment]
Отключил
