### ISSUE TITLE
Плагин OL не работает для наших WMS и WFS

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_opendata#17]
Сейчас долго ждет, потом ничего не отображает.
Возможно из-за кроссдомена или неверного формирования строки запрос GetCapabilities 

Например,
http://176.9.38.120/opendata_ngw/api/resource/473/wms

**Comment by drnextgis** [comment]
Ты про этот вьювер http://176.9.38.120/opendata/dataset/bojic/resource/f49b7606-2c93-47bb-9e16-aaf4a2b03c92 ? А WFS где смотреть?

**Comment by BishopGIS** [comment]
http://176.9.38.120/opendata/dataset/bojic/resource/3f6c296e-4905-4515-8d95-d105c64f3596
