### ISSUE TITLE
На больших наборах данных просмотр geojson вешает браузер

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_opendata#19]
Предлагаю как-то либо ограничить по зуму и экстенту или просто не показывать превью данных для таких объемов.
http://78.46.100.76/opendata/dataset/zemelnye-uchastki-po-kadastrovomu-deleniu/resource/c2d91118-4de1-4404-8b2c-fd7bc2a17e98
Ну или векторные тайлы.

**Comment by drnextgis** [comment]
@BishopGIS закрываем?
