### ISSUE TITLE
Увеличить лимит в прокси

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_opendata#20]
Увеличить лимит до 5 минут.
```
Could not load view: DataProxy returned an error (Request Error: Backend did not respond after 10 seconds)
```

**Comment by drnextgis** [comment]
Речь идёт про просмотрщик CSV данных Data Explorer?

**Comment by BishopGIS** [comment]
Да
16 янв. 2016 г. 13:29 пользователь "Denis Rykov" <notifications@github.com>
написал:

**Comment by drnextgis** [comment]
Сейчас мы перешли на DataStore и не используем DataProxy, который в будущем вообще [планируют](http://docs.ckan.org/en/latest/maintaining/data-viewer.html#data-explorer) выпилить:

```
Support for the DataProxy will be dropped on future CKAN releases
```

Сейчас большие датасеты отображаются нормально, [пример](http://78.46.100.76/opendata/dataset/zemelnye-uchastki-po-kadastrovomu-deleniu/resource/3435ba38-bec9-4cfd-85bd-4260d75c944e) (25k записей).

**Comment by BishopGIS** [comment]
Если проблема отображения решена - можно закрывать.

**Comment by drnextgis** [comment]
Загрузил все CSV в DataStore, при этом столкнулся со следующими проблемами, которые приводили к ошибкам:

1. В некоторых полях был текст 'NULL', но по первой записи DataStore определял, что это `numeric`, и когда доходил до 'NULL' - падал (исправил, отредактировав соответствующие ресурсы в NGW);
2. В некоторых полях в качестве разделителя разрядов была ',' (исправил, отредактировав соответствующие ресурсы в NGW);
3. DataStore пытается построит индекс по текстовым полям, а также индекс по полю полнотекстового поля, но поле с геометрией слишком большое - падение (исправил костылём в виде хардкода в 2-х местах: `datastore/helpers.py` и `datastore/db.py`);
4. Поле с геометрией слишком большое, вызывало падение библиотеки `messytables` (исправил захардкодив лимит на поле в 100Mb).
