### ISSUE TITLE
Добавить про NextGIS

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_opendata#21]
Сейчас в футере не упоминается NextGIS, хотя мы много сделали.
![2016-01-16 17-36-33](https://cloud.githubusercontent.com/assets/1708122/12372884/c27611c2-bc77-11e5-86f6-df509d229664.png)

**Comment by simgislab** [comment]
Создано NextGIS на базе CKAN

лучше так

**Comment by drnextgis** [comment]
Добавил нашу плашку:
![screenshot from 2016-01-18 16 29 33](https://cloud.githubusercontent.com/assets/866124/12389053/5779e074-bdf8-11e5-9913-1070b7c5c492.png)
