### ISSUE TITLE
Не отображаются русские буквы в режиме просмотра таблицы

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_opendata#23]
Возможно из-за того что не настроен datapusher.

http://82.162.194.216/ckan/dataset/moi-dokumenty/resource/31048636-48c2-4ce6-aea3-69a26b778b46

**Comment by drnextgis** [comment]
Да, данный документ не загружен в DataStore, поэтому он идёт через какой-то сторонний сервис, который перегоняет CSV в JSON, тут мы ничего поделать не можем, кроме как загрузить данные в DataStore.
