### ISSUE TITLE
Формирование шейп-файла "на лету"

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_opendata#4]
При скачивание шейп-файла пользователем на серверной стороне должен формироваться zip архив. Шейп-файл должен быть в глобальной системе координат World Geodetic System 1984 (WGS-84, код EPSG:4326). В архив должны добавляться файл prj описывающими систему координат данных и файл *.cpg описывающими кодировку атрибутивных данных (кодировка атрибутивных данных должна быть UTF-8).

**Comment by simgislab** [comment]
этот тикет кстати к НГВ, нет? он должен уметь такое формировать

**Comment by BishopGIS** [comment]
Если нормально получится наверное можно будет перенести в нгв. Хотя
geopackage перспективнее.

**Comment by BishopGIS** [comment]
Протестировано, работает, закрываю
