### ISSUE TITLE
Исправить CKAN

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_opendata#6]
1. Переделать CKAN на использование общей БД Postgres
2. Поставить модули в CKAN по работе с геоданными
  1. https://ckanext-spatial.readthedocs.org/en/latest/index.html без Spatial Harvesters и CSW support (пока не понятно нужен ли он)
  2. https://github.com/ckan/ckanext-geoview Обязательно выставить охват по Приморскому краю, вставить поиск по bbox на карте.

**Comment by drnextgis** [comment]
Добавил возможность задавать начальный охват для WMS слоёв, [пример](http://78.46.100.76/opendata/dataset/transport/resource/c258f9c8-bba3-4ca1-a95d-98813a1fbbce)

**Comment by BishopGIS** [comment]
@drnextgis Вроде все сделано? Закрываем?
