### ISSUE TITLE
Исправить оформление CKAN

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_opendata#7]
- [ ] Сделать оформление портала согласно стилю портала приморья.
- [ ] Сделать первую страницу информативной (описание портала, состав основных наборов, новые наборы, поиск).

**Comment by BishopGIS** [comment]
[] Вместо 420 х 220 вставить https://www.flickr.com/photos/descrier/16323834751/in/photolist-qStVmK-ikQYng-8Z9pht-bUBW9U-dkYNt8-bnp8nz-bnp8XX-pFUvT2-qixmSq-vyDWmX-eeeoU5-dq9qxc-dMwgDS-dQXAYm-r27SVE-q9A5A1-p2trWZ-knv9nk-knvL1T-knxo1C-knv6Mk-knxkSQ-qJg9Fi-pFQxrx-bCZgSZ-dCheHX-uUUxqj-pFUqA8-p2wubx-pY6KMk-pFQR9B-pFT9E3-vzj3jo-vRiVyW-pUr5fX-vRVs4X-vywKLy-vRVsjg-pUjnbf-peTbMm-peTfNh-qbP8rQ-qbGfqn-qbP51G-q9A6S9-q9A8cy-qbP6Cj-gFapdB-riAihh-yC4xvn

**Comment by BishopGIS** [comment]
- [ ] Редизайн согласно картинке
![design](https://cloud.githubusercontent.com/assets/1708122/10789741/42d87da4-7d90-11e5-819c-2a65e3425a10.png)

**Comment by simgislab** [comment]
- [ ] Вместо "Open Data" плиз "Открытые данные"

**Comment by netherbox** [comment]
Вот что получилось на текущий момент.

![ckan-fareast-theme-preview-1](https://cloud.githubusercontent.com/assets/5284449/10990393/d5f2b36e-8495-11e5-8dbd-8ddad042b45f.png)

**Comment by BishopGIS** [comment]
В основном стиль сделан, закрываю. Будут изменения - уже новые тикеты буду заводить.
